# Generated by Django 5.1.6 on 2025-02-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='display_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
