# Generated by Django 5.1.6 on 2025-02-19 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=100)),
                ('session', models.CharField(blank=True, default='', max_length=100)),
                ('general_market_condition', models.CharField(max_length=100)),
                ('intermediate_market_condition', models.CharField(max_length=100)),
                ('entry_market_condition', models.CharField(max_length=100)),
                ('entry_strategy', models.CharField(max_length=255)),
                ('trade_entry_description', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stoploss_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('entry_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=100)),
                ('manual_exit_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('time_executed', models.DateTimeField(blank=True, null=True)),
                ('trade_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.DecimalField(decimal_places=4, max_digits=10)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_targets', to='trades.trade')),
            ],
        ),
    ]
