# Generated by Django 5.1.6 on 2025-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profittarget',
            name='target',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stoploss_price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
