# Generated by Django 5.1.6 on 2025-02-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_profittarget_target_alter_trade_entry_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='order_type',
            field=models.CharField(default='market execution', max_length=100),
        ),
    ]
