# Generated by Django 5.1.6 on 2025-03-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade_order_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='time_executed',
            new_name='execution_time',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='trade_entry_description',
            new_name='trade_description',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='entry_market_condition',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='entry_strategy',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='general_market_condition',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='intermediate_market_condition',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='manual_exit_reason',
        ),
        migrations.AddField(
            model_name='trade',
            name='risk_reward_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='order_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='outcome',
            field=models.CharField(choices=[('Profit', 'Profit'), ('Loss', 'Loss'), ('Breakeven', 'Breakeven')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trade',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
