# Generated by Django 5.1.6 on 2025-02-14 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettingsView',
            new_name='UserAppSettings',
        ),
        migrations.RenameField(
            model_name='userappsettings',
            old_name='new_update',
            new_name='news_update',
        ),
    ]
