# Generated by Django 5.1.6 on 2025-02-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_usersettingsview_userappsettings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userappsettings',
            old_name='news_update',
            new_name='new_updates',
        ),
    ]
